### PR TITLE
updated dockerfile

### PR DESCRIPTION
**Pull request by hieutrn1205**
creating jupyterlab image

### CODE REVIEW

**Comment by joshbrinks** [comment]
I will merge this and remove the lines ADDing the local repo which 2i2c will not want. 

It's possible this build will not work on 2i2c with all the extraneous jupyter lab stuff. They have a specialized backend and so far have wanted a rocker/binder based build.

**Comment by hieutrn1205** [comment]
Please have it tested and let me know if it's not working.

**Comment by joshbrinks** [comment]
Worst case scenario it needs to be stripped down to the the packages being added with a rocker/binder base image. It would be nice if we could have the quarto extension, but maybe that's something 2i2c can do for us on their end.

**Comment by joshbrinks** [comment]
What lesson needs the arcgis stuff?

**Comment by hieutrn1205** [comment]
I don't know if that is a lesson or not. But the notebook is in the repo:
ndistem2024.ipynb

**Pull request merged**
